# Generated by Django 4.0.2 on 2022-02-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_clothes_clothestype_delete_type_clothes_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.IntegerField(default=15),
        ),
    ]
